name: Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ macos, ubuntu, windows ]

    steps:
      - if: matrix.os == 'windows'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check ./src
      - run: zig build --release=safe
        