name: release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ macos, ubuntu, windows ]

    steps:
      - if: matrix.os == 'windows'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check ./src
      - run: zig build --release=safe
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: ./zig-out/
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-ubuntu
        path: ./artifacts/ubuntu/
    - uses: actions/download-artifact@v4
      with:
        name: build-windows
        path: ./artifacts/windows/
    - uses: actions/download-artifact@v4
      with:
        name: build-macos
        path: ./artifacts/macos/

    - name: Compress artifacts
      run: |
        tar -czvf build-ubuntu.tar.gz ./artifacts/ubuntu/
        tar -czvf build-windows.tar.gz ./artifacts/windows/
        tar -czvf build-macos.tar.gz ./artifacts/macos/

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build-ubuntu.tar.gz,build-windows.tar.gz,build-macos.tar.gz"
    name: Create Release
